require("json2ify")
require("es5-shimify")
require("jqueryify")

require("spine")
require("spine/lib/local")
require("spine/lib/ajax")
require("spine/lib/manager")
require("spine/lib/route")
require("spine/lib/tmpl")